function chi_d = guidance(eta, last_wp, next_wp, lookahead_delta)

   [x_p, y_p, y_e_p] = crosstrack(next_wp(1),...
               next_wp(2),...
               last_wp(1),...
               last_wp(2),...
               eta(1),...
               eta(2));

    path_vector = next_wp - last_wp;
    pi_p = atan2(path_vector(2), path_vector(1));
    
    Kp = 1/lookahead_delta;
    chi_d = pi_p - atan(Kp*y_e_p);
 
end